### ISSUE TITLE
DFP contains/include operator (~) doesn't work?  (Possible DFP issue?)

### ISSUE THREAD

**Issue by creinhardt** [coop182/jquery.dfp.js#105] opened 2015-07-11 05:46 UTC
First off, a huge thanks for your work on this.  It's made working with DFP enjoyable, which is no small feat!

It's possible this is 100% a DFP issue, but thought i'd ask here in case anyone else had run into it.

I'm trying to target a line item using the UrlPath custom variable with the 'include/contains' (~) operator.  My UrlPath is /2015/07/politics-election/foo/ and my criteria is set to 'UrlPath is ~politics-election'.  I've confirmed that the UrlPath variable is being set by jquery.dfp.js by looking at the delivery diagnostics.  

No matter what I try DFP wont target the campaign.  Fiddling with delivery diagnostics, it seems to me that the ~ operator doesn't work.  DFP will only target the exact phrase (in my case 'politics-election'), not a segment of the UrlPath.

Has anyone else run into this or been able to get contains/include to work?

**Comment by creinhardt** [comment] 2015-07-15 23:20
Hah!  Just received this in an e-mail from DoubleClick.  Definitely nothing to do with dfp.jquery:

"Dear Customer,

We are currently experiencing an issue that is causing DoubleClick for Publishers Query Tool “contains” filters to be case sensitive. We are working to restore full functionality of the affected filters.

At this time we do not have an estimate for when this issue will be resolved. We will send an update by 5PM ET tomorrow, Thursday, July 16th.

Please note that ad serving is not affected.

We thank you for your patience and apologize for any inconvenience this may cause.

Regards,
The DoubleClick for Publishers Team"

**Comment by coop182** [comment] 2015-07-15 23:21
Yeah I just got that email as well! Sorry for the slow reply... but I guess this is the cause :smile:

**Comment by creinhardt** [comment] 2015-07-15 23:23
No worries at all!  Thanks so much for your work on this, it's much appreciated.

**Comment by creinhardt** [comment] 2015-07-16 21:53
Hmm, just got another e-mail from them about this, and i'm worried that they're only fixing this in the query tool.  I'm going to go try my hand on the Google Product forums...

"Dear Customer,

We are continuing to work to address the current case sensitivity of the DoubleClick for Publishers Query Tool “contains” filters.

We expect to resolve the issue by Tuesday, July 21st. Please note that this time frame is an estimate and may change.

Please note that ad serving is not affected.

We thank you for your patience and apologize for any inconvenience this may cause.

Regards,
The DoubleClick for Publishers Team
"

**Comment by coop182** [comment] 2015-07-22 22:01
Just got the email saying this is resolved... is this issue fixed now?

**Comment by creinhardt** [comment] 2015-08-26 19:31
Apologies for not responding to this sooner.

It doesn't look like Google/DFP actually fixed this.  If I set the targeting criteria to ~/test-page and the url is http://www.url.com/test-page the targeting works.  

If I set the criteria to ~page and visit http://www.url.com/test-page the targeting does not work.

This is 100% a DFP issue as far as I can tell.  You can go ahead and close if you want.

Maybe I'm just reading their documentation wrong? 

https://support.google.com/dfp_premium/answer/177381

_"Include" match_

_Use a tilde (~) at the beginning of a value to include values that have the entire word in them, in any location. For example, ~travel would match values like adventure travel and travel insurance, but not travelers or travelers insurance._

**Comment by soreng** [comment] 2015-08-26 20:22
Hi, i read the docs as the word "travel" is matched, not the string "travel". As stated, "travel" is not matched in "travelers" or "travelers insurance". It seems to be implemented as (pseudo code):

function tildeMatch(haystack, needle){
  if(needle.substring(0,1)=='~')needle=needle.substring(1);
  var words = haystack.split(' ');
  for(i=0;i<words.length;i++){
    if(words[i]==needle) return true;
  }
  return false;
}

**Comment by coop182** [comment] 2015-09-03 22:29
Yeah its looks like an their implementation only matches whole words... I think @soreng is right... probably not a lot we can do here... you could probably come up with your own custom function to take the URL and extract every possible combination of words you might want to match... it would be kind of similar to the way I used to have to things before the contains and starts with operators became available...

https://github.com/coop182/jquery.dfp.js/blob/dbb03002e9e6b2d1150848e6a91b00c97406285a/jquery.dfp.js#L319

I will close this for now... but feel free to reopen it if you think there is anything that can be done to improve things from this end.

**Closed by coop182** 2015-09-03 22:29 UTC
